defaults:
  - task: SingleStepTaskSimple
  - algo: ppo_continuous
  - _self_

exp_name:
track: True
seed:
torch_deterministic: True
wandb_project_name: whipping
wandb_group:
wandb_entity: baixianger
cuda: True # Nvida GPU
mps: False # Apple M chip
