defaults:
  - task: SingleStepTaskSimple
  - algo: ppo_continuous

exp_name: 
track: True
seed: 42
torch_deterministic: True
wandb_project_name: whipping
wandb_entity: baixianger
cuda: True # Nvida GPU
mps: False # Apple M chip
