total_timesteps: 100000 # 1000000
num_envs: 256 # 256
asynchronous: True
buffer_size: 2048 # 256 * 8
update_epochs: 20 # 10
batch_size: 128 # 64
learning_rate: 3e-4
anneal_lr: True
gamma: 0.99
gae_lambda: 0.95
hidden_dims: [64, 32]
action_dist: beta
norm_adv: True
clip_coef: 0.2
clip_vloss: True
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: 
